---
- hosts: all 
  become: yes
  become_method: sudo 
  tasks: 
    - name: Update apache
      package: 
        name: httpd
        state: latest
      notify: APACHE

  handlers:
    - name: APACHE
      systemd:
        name: httpd
        state: restarted

    # - name: set the state of the service
    #   systemd:
    #     name: "{{service}}"
    #     state: "{{state}}"    
    # service: service name
    # state: reloaded | restarted | started | stopped