- name: Install something
  hosts: all
  tasks:
    - name: gather os specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ ansible_distribution }}.yml"
      tags: vars 
    - name: Install in centos
      when: ansible_os_family == "RedHat"
      package:
        name: "{{ item}}"
      with_items:
        - telnet
        - vim
        - tree  
        state: present
