- name: Install something
  hosts: all
  tasks:
    - name: Install in centos
      when: ansible_os_family == "RedHat"
      package:
        name: "{{ item}}"
      with_items:
        - telnet
        - vim
        - tree 
        
    - name: Install in ubuntu
      when: ansible_os_family == "Ubuntu"
      apt:
        name: "{{ packages}}"
      vars:
        packages:
        - vim
        - tree
        - telnet
