- name: Install something
  hosts: all
  tasks:
    - name: Install in centos
      when: ansible_os_family == "RedHat"
      package:
        name: "{{ item}}"
      with_items:
        - telnet
        - vim
        - tree  
      state: present
    - name: Install in ubuntu
      when: ansible_os_family == "Ubuntu"
      package:
        name: "{{ item}}"
      with_items:
        - telnet
        - vim
        - tree  
      state: present
