---
- name: Do something
  hosts: all
  tasks:
    - name: archive
      archive:
        path: :"/tmp/"
        age: "90d"
        file_type: directory
      register: dirsOlderThan90d
        format: zip  
      
