---
- name: Do something
  hosts: all
  tasks:
    - name: find
      find:
        path: :"/tmp/"
        age: "90d"
        file_type: directory
      register: dirsOlderThan90d
- name: archive
  archive: 
    path: "{{ item.path}}"
    format: zip
      
